version: "3"
  services:
    web:
      image: k1r911/get-started:latest
      deploy:
        replicas: 5
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
        restart_policy:
          condition: on-failure
        ports:
        - "4000:80"
        networks:
        - webnet
    networks:
      webnet:
